### ISSUE TITLE
Saved results not returned

### ISSUE THREAD

**Issue by Ricky-Tigg** [niutech/html5test#14]
Hello. It would be futile to count the time that has passed since the captain of the source ship left it. All it takes is for anyone to take a look at the dates that are associated to the last commits of the resources to be convinced. Also the domain _html5test.com_ is a thing of the past. To you who have assigned yourself the heavy task of being captain of this fork-ship, It goes without saying that this branch will have to be ahead of the source branch of many other commits yet, so that the present project finally breaks the tradition of being only partially operational.

Yet during my very first test on the domain _html5test.co_, already an observable issue, a major one; none of the saved results are returned, in their respective fields, whether by **URL** or **ID code** attached to results.

**Comment by niutech** [comment]
It should be fixed by now.
