### ISSUE TITLE
Refreshing the page causes the loss of browsers selected as current browser

### ISSUE THREAD

**Issue by Ricky-Tigg** [niutech/html5test#17]
Hello. **Issue:** While among the browsers that are being selected for comparison, several of them are representing the current browser, refreshing (<kbd>f5</kbd>) the page causes to retain a single browser among the current browsers, thus without affecting the selection of browsers that were added as unique ID.

**Comment by niutech** [comment]
Could you give an example URL? For instance, when I load https://html5test.co/compare/browser/?1be0c667d1cb43d3/f9d95c679e0dfae8/mybrowser, all 3 browsers are being loaded even after refreshing page.

**Comment by niutech** [comment]
Why would anybody add the current browser twice? Once should be enough.

**Comment by niutech** [comment]
@Ricky-Tigg Instead of this lengthy argument, could you please provide a real-world case why you need two _current browser_ scores side by side?
