### ISSUE TITLE
The H265/HEVC detection does not work properly

### ISSUE THREAD

**Issue by anna-dolbina** [niutech/html5test#19]
The website shows H265 is not supported in the latest Google Chrome:

![308586858-14a3136e-1851-4830-87bc-93c6be7a3df9](https://github.com/niutech/html5test/assets/1564418/839d9321-f543-4fe3-b11e-b884fc8398b7)
Google Chrome itself supports H265 and is able to play the video at the following web page:
https://tools.woolyss.com/html5-audio-video-tester/?u=woolyss.com/f/hevc-aac-caminandes-3.mp4

It looks like this check does not work properly and should be fixed.

**Comment by niutech** [comment]
The code to detect H265 support is:

    var element = document.createElement('video');
    return !!element.canPlayType && (element.canPlayType('video/mp4; codecs="hvc1.1.L0.0"') == 'probably' || element.canPlayType('video/mp4; codecs="hev1.1.L0.0"') == 'probably')

Probably the codecs parameter has change since.

**Comment by anna-dolbina** [comment]
Yes, this seems to depend on the codecs parameter:
![image](https://github.com/niutech/html5test/assets/1564418/cee1379d-c514-4546-8431-71506aeae08b)

**Comment by anna-dolbina** [comment]
The following also works in Google Chrome:
```js
MediaSource.isTypeSupported('video/mp4; codecs="hvc1.1.6.L93.90"')
```

**Comment by niutech** [comment]
I've added the new codec signature.
