### ISSUE TITLE
"Other browsers" and "compare" pages are missing

### ISSUE THREAD

**Issue by aaronliu0130** [niutech/html5test#9]
Probably known but tracking issues are good
![image](https://github.com/niutech/html5test/assets/11874211/42428f13-587b-402d-aa37-a083087402c7)

**Comment by niutech** [comment]
Fixed.

**Comment by aaronliu0130** [comment]
Nice! Stats still aren't updated, so I hope that is planned

**Comment by niutech** [comment]
Yes, step by step.
